/**
 * Crisis Console — placeholder types.
 *
 * These types describe the response shapes the API will return when the
 * Admin Crisis Console phases ship (see admin-crisis-implementation-plan.md
 * Phases 1–5). They are deliberately authored *ahead* of the API so the
 * admin panel can build UI in parallel — values come from mocks until the
 * endpoints exist, then the import paths swap to OpenAPI-generated types.
 *
 * **Swap-out contract:** when API ships, replace each interface here with
 * the one generated by `bun run generate:types`. TypeScript will surface
 * every consumer that needs touching in one compile pass.
 */

// ─── Roles ─────────────────────────────────────────────────────────

export type AdminRole =
    | 'USER'
    | 'MODERATOR'
    | 'MANAGER'
    | 'ADMIN'
    | 'SUPERADMIN'

// ─── Webhook events (Phase 0 substrate; admin search lands in Phase 3) ──

export type WebhookProvider = 'XENDIT' | 'SUMSUB' | 'TWILIO' | 'BREVO'

export type VerificationStatus = 'PASSED' | 'FAILED' | 'SKIPPED'
export type VerificationMethod =
    | 'X_CALLBACK_TOKEN'
    | 'X_PAYLOAD_DIGEST'
    | 'X_TWILIO_SIGNATURE'
    | 'NONE'

export type ProcessingStatus = 'PENDING' | 'PROCESSED' | 'SKIPPED' | 'ERROR'

export type SkipReason =
    | 'token_mismatch'
    | 'signature_mismatch'
    | 'missing_event_or_data'
    | 'missing_reference'
    | 'txn_not_found'
    | 'user_not_found'
    | 'applicant_mismatch'
    | 'unhandled_event'
    | 'already_terminal'
    | 'status_guard'
    | 'delivery_failed'
    | 'undeliverable'
    | 'user_not_found_by_contact'

export interface WebhookEventSummary {
    _id: string
    provider: WebhookProvider
    route: string
    eventName: string | null
    receivedAt: string
    referenceId: string | null
    linkedTransactionId: string | null
    linkedUserId: string | null
    verification: {
        status: VerificationStatus
        method: VerificationMethod
        detail: string | null
    }
    processing: {
        status: ProcessingStatus
        skipReason: string | null
        durationMs: number | null
        sideEffects: Array<string>
    }
}

/**
 * Raw payload view — returned by `GET /admin/webhook-events/:id/payload`
 * (SUPERADMIN-only). `headers` are already presence-markers (no raw
 * secrets); `payload` is the provider body exactly as stored.
 */
export interface WebhookEventPayload {
    eventId: string
    provider: WebhookProvider
    route: string
    environment: string | null
    eventName: string | null
    receivedAt: string
    referenceId: string | null
    linkedTransactionId: string | null
    linkedUserId: string | null
    verification: {
        status: VerificationStatus
        method: VerificationMethod
        detail: string | null
    }
    processing: {
        status: ProcessingStatus
        skipReason: string | null
        errorMessage: string | null
        durationMs: number | null
        sideEffects: Array<string>
    }
    // Freeform provider data — typed `any` so the createServerFn return
    // satisfies its serializable constraint.
    headers: Record<string, any>
    payload: any
    payloadHash: string | null
    auditEntryId: string | null
}

// ─── Admin audit entries (Phase 1 model, Phase 2 helper) ────────────

export type AuditTargetModel =
    | 'User'
    | 'Plan'
    | 'Transaction'
    | 'Ticket'
    | 'WebhookEvent'

export type AuditResult = 'PREVIEW' | 'APPLIED' | 'FAILED'

export interface AdminAuditEntry {
    _id: string
    actor: { _id: string; displayName: string }
    actorRole: AdminRole
    action: string
    targetModel: AuditTargetModel
    targetId: string
    reason: string
    dryRun: boolean
    result: AuditResult
    webhookEventId: string | null
    createdAt: string
}

// ─── Unified timeline (Phase 3 — L1 read-only 360 views) ───────────

export type TimelineEventType =
    | 'webhook'
    | 'transaction'
    | 'kyc'
    | 'plan_lifecycle'
    | 'audit'
    | 'user_status'
    | 'application'
    | 'notification'
    | 'activity'

export interface TimelineEventBase<TKind extends TimelineEventType, TPayload> {
    id: string
    kind: TKind
    at: string
    summary: string
    payload: TPayload
}

/**
 * Per-user diagnostic event (signup + plan-creation outcomes) surfaced on
 * the User 360 timeline. Emitted by beens-api's diagnostic-events source so
 * an operator can see *why* a generic action failed (e.g. a plain
 * "Couldn't create the Plan. Try again" becomes "Plan create rejected —
 * invalid timezone"). Unlike the other kinds this row is flat — fields live
 * at the top level (no `payload`) and the timestamp arrives as `timestamp`.
 */
export interface TimelineActivityEvent {
    id: string
    kind: 'activity'
    timestamp: string
    outcome: 'OK' | 'FAILED'
    status: number
    route: string
    reason: string | null
    summary: string
}

export type TimelineEvent =
    | TimelineEventBase<'webhook', WebhookEventSummary>
    | TimelineEventBase<
            'transaction',
            {
                transactionId: string
                status: string
                escrowReleaseStatus: string | null
                amount: number
                currency: string
            }
        >
    | TimelineEventBase<
            'kyc',
            {
                applicantId: string
                kycStatus: string
                sumsubReviewStatus: string | null
            }
        >
    | TimelineEventBase<
            'plan_lifecycle',
            {
                planId: string
                planTitle: string
                from: string
                to: string
            }
        >
    | TimelineEventBase<'audit', AdminAuditEntry>
    | TimelineEventBase<
            'user_status',
            { from: string; to: string; reason: string | null }
        >
    | TimelineEventBase<
            'application',
            {
                applicationId: string
                planId: string
                planTitle: string
                status: string
                expiredReason: string | null
            }
        >
    | TimelineEventBase<
            'notification',
            { type: string; title: string; channel: 'push' | 'email' | 'sms' }
        >
    | TimelineActivityEvent

// ─── Remediation actions (Phase 5) ──────────────────────────────────

export type RemediationActionKey =
    | 'replay_webhook'
    | 'reconcile_transaction'
    | 'force_transaction_status'
    | 'resync_kyc'
    | 'allow_kyc_resubmit'
    | 'resend_otp'
    | 'verify_contact'
    | 'unstick_incomplete'
    | 'reset_code_attempts'
    | 'reissue_code'
    | 'force_join'
    | 'mark_participant_status'
    // Phase 9 — phantom On-Hold + ghosted-application resolve actions (§16.4)
    | 'reverse_failed_splits'
    | 'process_ghosted'
    | 'resend_expiry_notice'

export interface RemediationAction {
    key: RemediationActionKey
    label: string
    minRole: AdminRole
    /** Recommended button — drawn from the §7.4 decision table by signal. */
    recommended: boolean
}

export interface RemediationContext {
    targetModel: AuditTargetModel
    targetId: string
    /** Recommended sentence the operator sees ("Payment confirmed but verification failed (config issue)"). */
    summary: string
    /** Source-of-truth comparison rendered in DivergenceCard. */
    divergence?: {
        dbValue: string
        providerValue: string
        cause: string | null
    }
    /** Stored webhook event the signal was derived from. Populated when
     *  the action is `replay_webhook` so the panel can target
     *  `/admin/webhook-events/:id/replay` without a second lookup. */
    webhookEventId?: string | null
    /**
     * Phase 9 — the FAILED transaction the phantom signal derives from.
     * Populated by the backend remediation-context when a
     * `reverse_failed_splits` action is offered on a host's User 360 (the
     * reverse endpoint is transaction-scoped: POST
     * /admin/transactions/:id/reverse-failed-splits). Falls back to
     * `targetId` when the context itself targets a Transaction.
     */
    transactionId?: string | null
    /**
     * Phase 9 — the Application a ghost signal derives from. Populated when
     * a `process_ghosted` / `resend_expiry_notice` action is offered (both
     * endpoints are application-scoped: POST /admin/applications/:id/...).
     */
    applicationId?: string | null
    actions: Array<RemediationAction>
}

export interface RemediationApplyResponse {
    success: boolean
    result: AuditResult
    auditEntryId: string
    /** When dryRun, a plain-language preview of the change. */
    diffSummary?: string
}
